### ISSUE TITLE
Podspec issue

### ISSUE THREAD

**Issue by johnryan** [jamesjhu/XCTestAsync#1]
Hi,

I really like your implementation of async tests. Is there any reason why the minimum version is 7.0?

Thanks!

**Comment by jamesjhu** [comment]
Thanks. I set the minimum version to 7.0 due to the fact that XCTest is only available in the iOS 7.0 SDK and newer. If need to test against an older version of the SDK, you can use [nxtbgthng/SenTestingKitAsync](https://github.com/nxtbgthng/SenTestingKitAsync)

**Comment by johnryan** [comment]
James, I thought that the deployment target parameter controls the OS version of the device, not the SDK. The iOS7 SDK can build apps that can be installed on ios 6.

http://stackoverflow.com/questions/3703612/iphone-app-basesdk-and-ios-deployment-target

**Comment by jamesjhu** [comment]
Thanks, I removed the deployment target from the spec.
https://github.com/CocoaPods/Specs/pull/8386

**Comment by johnryan** [comment]
Awesome, thanks a lot.

-John
